version: '3'

services:

  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: dbuser

  web:
    restart: always
    build: .
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - static:/www
    # env_file: .env
    environment:
      DEBUG: 'True'
      DB_ENGINE: 'django.db.backends.postgresql'
      DB_NAME: 'postgres'
      DB_USER: 'dbuser'
      DB_PASSWORD: 'postgres' 
      DB_HOST: 'postgres'
      STATIC_ROOT: '/www/static'
      MEDIA_ROOT: '/www/media'
      SECRET_KEY: '!nbkyn4osdgpzggv)(9w=&u_a((f!k9=m^bo%$1knzya%7-e++'
      VITE_API_URL: '/api/'

  nginx:
    restart: always
    build: ./nginx/
    depends_on:
      - web
    ports:
      - "8080:80"
    volumes:
      - static:/usr/share/nginx/html
      - certbot_conf:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    volumes:
      - certbot_conf:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"


volumes:
  static:
  postgres_data:
  certbot_conf:
  certbot_www: