services:

  postgres:
    environment:
      POSTGRES_PASSWORD: ''
      POSTGRES_PASSWORD_FILE: '/run/secrets/db_password'
    secrets:
      - db_password


  web:
    build:
      context: .
    environment:
      DEBUG: 'True'

      DB_PASSWORD: '/run/secrets/db_password'
      SECRET_KEY: '/run/secrets/secret_key'
      ALLOWED_HOSTS: 'api.oboz.samorzad.pwr.edu.pl,www.api.oboz.samorzad.pwr.edu.pl'
      CSRF_TRUSTED_ORIGINS: 'http://localhost:8100'

    secrets:
      - secret_key
      - db_password
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    ports:
      - "80:80"
      - "443:443"

secrets:
  secret_key:
    file: /secrets/secret_key_production.txt
  db_password:
    file: /secrets/db_password.txt