services:

  postgres:
    environment:
      POSTGRES_PASSWORD: ''
      POSTGRES_PASSWORD_FILE: '/run/secrets/db_password'
    secrets:
      - db_password


  web:
    environment:
      DEBUG: 'False'

      EMAIL_BACKEND: 'django.core.mail.backends.smtp.EmailBackend'
      DEFAULT_FROM_EMAIL: 'Obóz Studentów PWr 2023 <obozstudentow2023@e-2-e.eu>'
      EMAIL_HOST: 'smtp.office365.com'
      EMAIL_HOST_USER: 'marvin.rucinski@e-2-e.eu'
      EMAIL_HOST_PASSWORD: 'REMOVED'
      EMAIL_PORT: 587
      EMAIL_USE_TLS: 'true'
      EMAIL_USE_SSL: 'false'

      DB_PASSWORD: '/run/secrets/db_password'
      SECRET_KEY: '/run/secrets/secret_key'
      ALLOWED_HOSTS: '130.61.148.125,appka.obozstudentowpwr.com,apka.obozstudentowpwr.com,test.obozstudentowpwr.com,test3.obozstudentowpwr.com'
      CSRF_TRUSTED_ORIGINS: 'https://appka.obozstudentowpwr.com,https://apka.obozstudentowpwr.com,https://test.obozstudentowpwr.com'
    secrets:
      - secret_key
      - db_password
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    ports:
      - "80:80"
      - "443:443"

secrets:
  secret_key:
    file: /secrets/secret_key_production.txt
  db_password:
    file: /secrets/db_password.txt